### ISSUE TITLE
Add notes to README about prezto fork history

### ISSUE THREAD

**Issue by mafrosis** [zimframework/zim#9]
It's really unclear what this framework offers over prezto, especially given it's a fork.

The new zsh-users/prezto project should probably be considered too

**Comment by Eriner** [comment]
It's not a fork.

**Comment by mafrosis** [comment]
Wow thanks for the clarification

**Comment by Eriner** [comment]
You probably want to take a look at this: https://github.com/Eriner/zim, which is the primary repository. Alternatively, if you're up for some (heavier) reading, I'm pretty sure we've summarized the whole situation in this thread on this repo: https://github.com/zimframework/zim/issues/2

**Comment by mafrosis** [comment]
Thanks for clearing that up. I think this info should be in the README!

Zim may not be a fork in the strict sense, but (without having done a deep dive) the vast majority of your modules seem to have been imported from prezto without attribution. (However, I appreciate you appear have done a decent amount of work on them)

**Comment by Eriner** [comment]
> the vast majority of your modules seem to have been imported from prezto without attribution

This is not the case, as most of the inspiration from prezto I'm referring to comes down to code structure, not code contents. The places that uses code from prezto [such as the git module aliases](https://github.com/Eriner/zim/blob/master/modules/git/README.md), have attribution.
